name: Publish Lists to GitHub

on:
  schedule:
    - cron: '0 6 * * */3'
  workflow_dispatch:

jobs:
  github:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: dist

      # Max thread count is 204822, as given by `cat /proc/sys/kernel/threads-max`
      # https://askubuntu.com/questions/1006377/check-the-max-allowed-threads-count-for-sure#1006384
      - name: Generate lists
        run: |
          curl --proto '=https' --tlsv1.3 -H 'Accept: application/vnd.github.v3+json' -sSf https://api.github.com/repos/T145/black-mirror/releases/latest | jq -r '.assets[] | select(.name | endswith("txt")).browser_download_url' | aria2c -i- -d ./assets --conf-path='./configs/aria2.conf'
          dnsx -r ./configs/resolvers.txt -l ./assets/black_domain*.txt -o ./dist/black_nxdomain.txt -c 200000 -silent -rcode nxdomain
          mawk '{print $1}' ./dist/black_nxdomain.txt | sponge ./dist/black_nxdomain.txt
        shell: bash

      - name: Commit updated lists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # homage to the python linting utility "black"
          commit_message: ✨🍰✨
          branch: dist
          file_pattern: dist/*.txt
