name: Publish Lists to GitHub

on:
  schedule:
    - cron: '0 6 * * */3'
  workflow_dispatch:

jobs:
  github:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Max thread count is 204822, as given by `cat /proc/sys/kernel/threads-max`
      # https://askubuntu.com/questions/1006377/check-the-max-allowed-threads-count-for-sure#1006384
      - name: Generate lists
        run: |
          curl --proto '=https' --tlsv1.3 -H 'Accept: application/vnd.github.v3+json' -sSf https://api.github.com/repos/T145/black-mirror/releases/latest | jq -r '.assets[] | select(.name | endswith("txt")).browser_download_url' | aria2c -i- -d ./assets --conf-path='./configs/aria2.conf'
          dnsx -r ./configs/resolvers.txt -hf ./dist/black_nxdomain.txt -l ./assets/black_domain*.txt -o ./assets/black_nxdomain.txt -c 200000 -silent -rcode nxdomain 1> /dev/null
          mawk '{print $1}' ./assets/black_nxdomain.txt | comm ./dist/black_nxdomain.txt - -13 >>./dist/black_nxdomain.txt
          parsort -u -S 100% --parallel=200000 -o ./dist/black_nxdomain.txt ./dist/black_nxdomain.txt
          rm -rf ./assets/*.txt
        shell: bash

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: latest
          prerelease: false
          title: All Artifacts
          files: dist/*.txt

      - name: Get release data
        id: release_data
        uses: KevinRohn/github-full-release-data@v2.0.2
        with:
          token: ${{ github.token }}

      - name: Update changelog
        if: steps.release_data.outputs.body != 'null'
        run: |
          echo -n '## ' >>CHANGELOG.md
          date +"%d-%m-%Y %T" >>CHANGELOG.md
          echo "${{ fromJSON(steps.release_data.outputs.body) }}" | sed 1d >>CHANGELOG.md
        shell: bash

      - name: Reset branch history
        if: 'success'
        run: |
          git checkout --orphan latest
          git add -A
          git commit -am "✨🍰✨"
          git branch -D master
          git branch -m master
          git push -f origin master
        shell: bash
