name: Publish Lists

on:
  schedule:
    - cron: '0 6 * * */3'
  workflow_dispatch:

jobs:
  github:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate lists
        id: build
        run: ./scripts/github/workflow.bash
        shell: bash

      - name: Dump output context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        shell: bash

      - name: Create GitHub release
        if: steps.build.outputs.status == 'success'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: latest
          prerelease: false
          title: All Artifacts
          files: dist/*

      - name: Update documents
        if: steps.build.outputs.status == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # homage to the python linting utility "black"
          commit_message: ✨🍰✨
